{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f543b1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#1. \n",
    "\n",
    "In Python, an Exception is an event that occurs during the execution of a program that disrupts the normal flow of instructions. \n",
    "When an exceptional situation occurs, such as an error or an unexpected condition, Python raises an Exception to handle it.\n",
    "\n",
    "Here are the main differences between Exceptions and Syntax errors in Python:\n",
    "\n",
    "Exceptions:\n",
    "\n",
    "1. Exceptions occur during the runtime of the program.\n",
    "2. They are typically caused by unexpected conditions or errors in the program's logic or input data.\n",
    "3. Examples of exceptions include division by zero (ZeroDivisionError), trying to access an element outside the bounds of a list (IndexError), or attempting to convert an invalid string to an integer (ValueError).\n",
    "\n",
    "Syntax Errors:\n",
    "\n",
    "1. Syntax errors, also known as parsing errors, occur during the compilation phase before the program starts executing.\n",
    "2. They are caused by violations of the Python syntax rules. It means there is a mistake in the way the code is written.\n",
    "3. Examples of syntax errors include forgetting a colon (:) after an if statement, mismatched parentheses, or incorrect indentation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9565c82a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#2. \n",
    "\n",
    "When an exception is not handled in Python, it results in the termination of the program's normal execution and an error message is displayed to the user.\n",
    "\n",
    "Example:\n",
    "    \n",
    "def divide_numbers(a, b):\n",
    "    return a / b\n",
    "\n",
    "try:\n",
    "    num1 = int(input(\"Enter the first number: \"))\n",
    "    num2 = int(input(\"Enter the second number: \"))\n",
    "    result = divide_numbers(num1, num2)\n",
    "    print(\"Result of division:\", result)\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Please enter valid integers.\")\n",
    "\n",
    "In this example, the user is prompted to enter two numbers. \n",
    "If the user enters valid integers, the program proceeds to divide the first number by the second number and displays the result. \n",
    "However, if the user enters non-integer inputs, a ValueError will be raised when converting the inputs to integers, and the program will catch this exception using the except ValueError block. \n",
    "The user will be informed that the input is invalid, and the program will not crash.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35515008",
   "metadata": {},
   "outputs": [],
   "source": [
    "#3.\n",
    "\n",
    "In Python, the try, except, and finally statements are used to catch and handle exceptions. \n",
    "\n",
    "Example:\n",
    "    \n",
    "try:\n",
    "    num1 = int(input(\"Enter the first number: \"))\n",
    "    num2 = int(input(\"Enter the second number: \"))\n",
    "    result = num1 / num2\n",
    "    print(\"Result of division:\", result)\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Please enter valid integers.\")\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero is not allowed.\")\n",
    "finally:\n",
    "    print(\"Execution completed.\")\n",
    "\n",
    "In this example, regardless of whether an exception occurs or not, the finally block will always be executed. \n",
    "It will print \"Execution completed.\" at the end of the try-except block's execution."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "770a9337",
   "metadata": {},
   "outputs": [],
   "source": [
    "#4.\n",
    "\n",
    "a.try and else:\n",
    "\n",
    "try:\n",
    "    num1 = int(input(\"Enter the first number: \"))\n",
    "    num2 = int(input(\"Enter the second number: \"))\n",
    "    result = num1 / num2\n",
    "except ValueError:\n",
    "    print(\"Invalid input. Please enter valid integers.\")\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero is not allowed.\")\n",
    "else:\n",
    "    print(\"Division successful.\")\n",
    "    print(\"Result of division:\", result)\n",
    "    \n",
    "b. finally\n",
    "\n",
    "try:\n",
    "    file = open(\"example.txt\", \"r\")\n",
    "    content = file.read()\n",
    "    print(content)\n",
    "except FileNotFoundError:\n",
    "    print(\"File not found.\")\n",
    "finally:\n",
    "    file.close()\n",
    "    print(\"File closed.\")\n",
    "    \n",
    "c. raise\n",
    "\n",
    "try:\n",
    "    age = int(input(\"Please enter your age: \"))\n",
    "    if age < 0:\n",
    "        raise ValueError(\"Age cannot be negative.\")\n",
    "    print(\"Valid age.\")\n",
    "except ValueError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81a05e12",
   "metadata": {},
   "outputs": [],
   "source": [
    "#5.\n",
    "\n",
    "Custom Exceptions in Python are user-defined exception classes that allow you to create your own exception types to represent specific error scenarios. \n",
    "They improve code clarity, enable specific error handling, promote modularity, and aid in error propagation.\n",
    "\n",
    "Example:\n",
    "\n",
    "class CustomError(Exception):\n",
    "    pass\n",
    "\n",
    "def my_function(value):\n",
    "    if value < 0:\n",
    "        raise CustomError(\"Invalid value: cannot be negative.\")\n",
    "\n",
    "try:\n",
    "    my_value = -5\n",
    "    my_function(my_value)\n",
    "except CustomError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c932a990",
   "metadata": {},
   "outputs": [],
   "source": [
    "#6.\n",
    "\n",
    "class InvalidInputError(Exception):\n",
    "    def __init__(self, message):\n",
    "        self.message = message\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    if b == 0:\n",
    "        raise InvalidInputError(\"Cannot divide by zero.\")\n",
    "    return a / b\n",
    "\n",
    "try:\n",
    "    num1 = int(input(\"Enter the first number: \"))\n",
    "    num2 = int(input(\"Enter the second number: \"))\n",
    "    result = divide_numbers(num1, num2)\n",
    "    print(\"Result of division:\", result)\n",
    "\n",
    "except InvalidInputError as e:\n",
    "    print(e)\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
